---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# - name: configure keystone.conf file
#  ini_file:
#    dest: /etc/keystone/keystone.conf
#    group: keystone
#    mode: 0640
#    section: "{{ item.section }}"
#    option: "{{ item.option }}"
#    value: "{{ item.value }}"
#  with_items:
#     - { section: DEFAULT, option: admin_token, value: 5b593d4553ff16d35904 }
#     - { section: DEFAULT, option: rabbit_hosts, value: "10.9.28.152:5672,10.9.28.153:5672,10.9.28.154:5672" }
#     - { section: DEFAULT, option: rabbit_ha_queues, value: true }
#     - { section: DEFAULT, option: verbose, value: true }
#     - { section: database, option: connection, value: "mysql://keystone:{{ keystone_database_pass }}@{{ openstack_ha_vip  }}/keystone" }
#     - { section: memcached, option: servers, value: "10.9.28.152:11211,10.9.28.153:11211,10.9.28.154:11211" }
#     - { section: token, option: provider, value: uuid }
#     - { section: token, option: driver, value: sql }
#     - { section: revoke, option: driver, value: sql }
#
#  register: modify_keystone_ini

- name: copy keystone.conf file
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf

# - name: set db host to local ip
#  shell: sed -i '/connection/s/{{ openstack_ha_domain }}/{{ inventory_hostname }}/g' /etc/keystone/keystone.conf

- name: ensure keystone database has been synced
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  become: yes
  become_user: root

- name: configure apache httpd file
  command: sed -i 's/Listen 80/Listen {{inventory_hostname}}:80/g' /etc/httpd/conf/httpd.conf

- name: add keystone apache configure file
  template: src=openstack-keystone.conf.j2 dest=/etc/httpd/conf.d/openstack-keystone.conf
  notify: restart keystone

- name: copy keystone rc file
  template: src=keystone-rc.sh.j2 dest=/root/keystone-rc.sh owner=root mode=0600

- name: copy admin openrc file
  template: src=admin-openrc.sh.j2 dest=/root/admin-openrc.sh owner=root mode=0600

- name: restart httpd
  service: name=httpd state=restarted enabled=yes

- name: restart memcached
  service: name=memcached state=restarted enabled=yes

- name: sleep 10s
  shell: sleep 10
