---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- name: create keystone database
  mysql_db: name=keystone login_user=root login_password={{ mysql_root_password }} state=present

- name: grant access to the keystone database
  mysql_user: name=keystone host="{{ item }}" login_user=root login_password={{ mysql_root_password }} password={{ keystone_database_pass }} priv=keystone.*:ALL
  with_items:
    - localhost
    - "%"
