---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- include: packages.yml
  tag: package

- include: db.yml
  tag: db
  when: service_create == "once"

- include: configure.yml
  tag: configure

- include: service.yml
  tag: service
  when: service_create == "once"

# - name: reset db host to vip domain
#  shell: sed -i '/connection/s/{{ inventory_hostname }}/{{ openstack_ha_domain }}/g' /etc/keystone/keystone.conf
# 
# - name: restart httpd
#   service: name=httpd state=restarted enabled=yes
# 
# - name: restart memcached
#   service: name=memcached state=restarted enabled=yes
# 
