---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- include: packages.yml
  tag: package

- name: creates glance store directory
  file: path=/data/glance/images state=directory owner=glance group=glance mode=0775 recurse=yes
