---

#
# Copyright (c) 2016 feythin lau <feythin.lau@gmail.com>
#

- name: Install glance service and client
  yum: name={{ item }} state=present
  with_items:
    - openstack-glance
    - python-glance
    - python-glanceclient
