---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- name: configure manager interface
  template: src=ifcfg-manager.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ manager_interface }}

- name: configure data interface
  template: src=ifcfg-data.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ data_interface }}

# - name: configure data bridge
#   copy: src=ifcfg-br-int dest=/etc/sysconfig/network-scripts/ifcfg-br-int

- name: add bridge br-vlan
  shell: ovs-vsctl add-br br-vlan
  run_once: true

- name: add data interface to br-vlan
  shell: ovs-vsctl add-port br-vlan {{ data_interface }}
  run_once: true

- name: copy module 8021q
  copy: src=8021q.modules dest=/etc/sysconfig/modules/8021q.modules mode=0755

- name: modprobe 8021q
  command: modprobe 8021q
