---

#
# Copyright (c) 2016 feythin lau <feythin.lau@gmail.com>
#

- name: Install nova compute service
  yum: name={{ item }} state=present
  with_items:
    - openstack-nova-compute-12.0.1-1.el7.noarch
    - sysfsutils
    - openstack-utils
    - centos-release-qemu-ev
    - qemu-kvm-ev
