---

#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# service_create 变量主要是让创建service只在一台机器上操作，只创建一次就可以

- name: install and config keepalived
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-ha-keepalived[0]
  roles:
    - { role: openstack-ha-keepalived, keepalived_vip_ip: "10.100.24.180", keepalived_role: "MASTER" }

- name: install and config keepalived
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-ha-keepalived:!openstack-ha-keepalived[0]
  roles:
    - { role: openstack-ha-keepalived, keepalived_vip_ip: "10.100.24.180", keepalived_role: "BACKUP" }
