---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- name: check rabbitmq install or not
  shell: rpm -qa | grep rabbitmq-server-3.3.5-17 | wc -l
  register: rabbitmq_status

- name: if rabbitmq already install and runing , interrupt install
  fail: msg="rabbitmq already running"
  when: rabbitmq_status.rc != 0

- name: install rabbitmq
  yum: name="{{ item }}" state=present
  with_items:
    - rabbitmq-server

- name: copy cookie file
  copy: src=.erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0400

- name: enable rabbitmq service
  service: name=rabbitmq-server state=started enabled=yes
  notify: restart rabbitmq

#- name: echo rabbitmq_master
#  shell: echo "{{ rabbitmq_master }}"
#  register: rabbitmq_master_value

- name: stop rabbitmq app
  shell: rabbitmqctl stop_app
  when: rabbitmq_master == "slave"

- name: reset rabbitmq
  shell: rabbitmqctl reset
  when: rabbitmq_master == "slave"

- name: join rabbitmq master
  shell: rabbitmqctl join_cluster --ram rabbit@{{cluster_name}}
  when: rabbitmq_master == "slave"

- name: start rabbitmq app
  shell: rabbitmqctl start_app
  when: rabbitmq_master == "slave"
