---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- name: copy nova.conf file
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

# - name: set db host to local ip
#   shell: sed -i '/connection/s/{{ openstack_ha_domain }}/{{ inventory_hostname }}/g' /etc/nova/nova.conf

- name: ensure nova database has been synced
  command: su -s /bin/sh -c "nova-manage db sync" nova

- name: copy admin openrc file
  template: src=admin-openrc.sh.j2 dest=/root/admin-openrc.sh owner=root mode=0600

- name: enable and restart openstack-nova-api
  service: name=openstack-nova-api state=restarted enabled=yes

- name: enable and restart openstack-nova-cert
  service: name=openstack-nova-cert state=restarted enabled=yes

- name: enable and restart openstack-nova-consoleauth
  service: name=openstack-nova-consoleauth state=restarted enabled=yes

- name: enable and restart openstack-nova-scheduler
  service: name=openstack-nova-scheduler state=restarted enabled=yes

- name: enable and restart openstack-nova-conductor
  service: name=openstack-nova-conductor state=restarted enabled=yes

- name: enable and restart openstack-nova-novncproxy
  service: name=openstack-nova-novncproxy state=restarted enabled=yes
