---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- name: create glance user
  shell: source /root/admin-openrc.sh && openstack user create nova --domain default --password {{ keystone_auth_nova_password }}
  run_once: true

- name: add admin role to service project and nova user
  shell: source /root/admin-openrc.sh && openstack role add --project service --user nova admin
  run_once: true

- name: create nova service indentity
  shell: source /root/admin-openrc.sh && openstack service create --name nova --description "OpenStack Compute" compute
  run_once: true

- name: create glance public endpoint
  shell: source /root/admin-openrc.sh && openstack endpoint create --region {{ openstack_region }} compute public {{ nova_endpoint }}
  run_once: true

- name: create glance internal endpoint
  shell: source /root/admin-openrc.sh && openstack endpoint create --region {{ openstack_region }} compute internal {{ nova_endpoint }}
  run_once: true

- name: create glance admin endpoint
  shell: source /root/admin-openrc.sh && openstack endpoint create --region {{ openstack_region }} compute admin {{ nova_endpoint }}
  run_once: true
