---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- name: set sysctl ip_forward
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: set sysctl all rp_filter
  sysctl: name="net.ipv4.conf.all.rp_filter" value=0 sysctl_set=yes state=present reload=yes

- name: set sysctl default rp_filter
  sysctl: name="net.ipv4.conf.default.rp_filter" value=0 sysctl_set=yes state=present reload=yes

- name: set soft link plugin.ini
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link

- name: copy admin openrc file
  template: src=admin-openrc.sh.j2 dest=/root/admin-openrc.sh owner=root mode=0600

- name: restart nova service
  service: name={{ item }} state=restarted
  with_items:
    - libvirtd
    - openstack-nova-compute
