---

#
# Copyright (c) 2016 feythin lau <feythin.lau@gmail.com>
#

- name: Install os base service
  yum: name={{ item }} state=present
  with_items:
    - net-tools
    - telnet
    - bash-completion
    - vim
    - wget
    - tcpdump
    - traceroute
