---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- name: set hosts on all openstack hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: set static hostname
  shell: hostnamectl --static set-hostname "{{ hostname }}"

- name: set transient hostname
  shell: hostnamectl --transient set-hostname "{{ hostname }}"

- name: set timezone
  shell: timedatectl set-timezone Asia/Shanghai

- name: copy resolv.conf file
  copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
