---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- name: upgrade all packages
  yum: name=* state=latest

- name: reboot server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
