---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#


- name: install rabbitmq master
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq[0]
  roles:
     - { role: openstack-rabbitmq, rabbitmq_master: master }

- name: install rabbitmq slave
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq:!openstack-rabbitmq[0]
  roles:
     - { role: openstack-rabbitmq, rabbitmq_master: slave }

- name: set quene mirroring
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq[0]
  tasks:
      - name : enable queue mirroring
        shell: rabbitmqctl set_policy ha-all "\.*" '{"ha-mode":"all"}'

- name: add openstack user and add read write permissions
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq[0]
  tasks:
    - name: add openstack user
      shell: rabbitmqctl add_user openstack RABBIT_PASS
    - name: add read write permissions for openstack user
      shell: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
