---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- name: check mariadb install or not
  shell: rpm -qa | grep mariadb-5.5.47 | wc -l
  register: maraidb_status

- name: if maraidb already install and runing, interrupt install
  fail: msg="maraidb already runing"
  when: maraidb_status.rc != 0

- name: install mariadb
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-galera-server
    - mariadb-galera-common
    - galera
    - MySQL-python
    - rsync

- name: mariaDB configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0644
  notify: restart mariadb

- name: galera configuration file
  template: src=galera.cnf.j2 dest=/etc/my.cnf.d/galera.cnf owner=root group=root mode=0640
  notify: restart mariadb

- name: start and enable mariadb service
  service: name=mariadb state=started enabled=yes
  notify: restart mariadb

- include: mysql_secure_installation.yml
  when: galera_master == "master"

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv="*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
