---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- include: db.yml
  tag: db

- include: service.yml
  tag: service
  when: service_create == "once"

- include: packages.yml
  tag: package

- include: configure.yml
  tag: configure

# - name: reset db host to vip domain
#  shell: sed -i '/connection/s/{{ inventory_hostname }}/{{ openstack_ha_domain }}/g' /etc/neutron/neutron.conf

- name: restart nova service
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor

- name: restart neutron
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - openvswitch
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-openvswitch-agent
    - neutron-server
