---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- name: restart mariadb
  service: name=mariadb state=restarted

- name: start mariadb
  service: name=mariadb state=started

- name: stop mariadb
  service: name=mariadb state=stopped
