---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- name: copy HAProxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg backup=yes

- name: set sysctl ip_nonlocal_bind
  sysctl: name="net.ipv4.ip_nonlocal_bind" value=1 sysctl_set=yes state=present reload=yes

- name: enable and restart haproxy
  service: name=haproxy state=restarted enabled=yes
