keepalived_auth_pass: "yunzong_passwd"
keepalived_role: "MASTER"
keepalived_router_id: "52"
keepalived_vip_iface: "eth0"
keepalived_vip_ip: "192.168.1.1"
keepalived_check_process: "keepalived"
keepalived_priority: "100"
