---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- include: packages.yml
  tag: package

- include: configure.yml
  tag: configure
  when: run_type == "once" 

- include: reboot.yml
  tag: reboot
