---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- name: install rabbitmq
  yum: name="{{ item }}" state=present
  with_items:
    - rabbitmq-server

- name: copy cookie file
  copy: src=.erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0400
