---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
- include: db.yml
  tag: db
  when: service_create == "once"

- include: service.yml
  tag: service
  when: service_create == "once"

- include: packages.yml
  tag: package

- include: configure.yml
  tag: configure

# - name: reset db host to vip domain
#   shell: sed -i '/connection/s/{{ inventory_hostname }}/{{ openstack_ha_domain }}/g' /etc/glance/glance-api.conf
# 
# - name: reset db host to vip domain
#   shell: sed -i '/connection/s/{{ inventory_hostname }}/{{ openstack_ha_domain }}/g' /etc/glance/glance-registry.conf
# 
# - name: restart openstack-glance-api
#   service: name=openstack-glance-api state=restarted enabled=yes
# 
# - name: restart openstack-glance-registry
#   service: name=openstack-glance-registry state=restarted enabled=yes
