---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

- name: install openstack common
  hosts: 10.100.24.31
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network, manager_interface: enp2s0, data_interface: enp3s0, wan_interface: enp3s1,  manager_gateway: 10.100.24.254, wan_gateway: 10.200.24.254 }

- name: install openstack common
  hosts: 10.100.24.32
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network, manager_interface: enp2s0, data_interface: enp3s0, wan_interface: enp3s1,  manager_gateway: 10.100.24.254, wan_gateway: 10.200.24.254 }

- name: install openstack common
  hosts: 10.100.24.33
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network, manager_interface: enp2s0, data_interface: enp3s0, wan_interface: enp3s1,  manager_gateway: 10.100.24.254, wan_gateway: 10.200.24.254 }
