---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# 1. 由于升级系统后，repository会加入系统自带的源，这里要删除自带源，用自己内网的centos源
# 2. 安装和配置网卡。由于每台机器的网卡interface不一样，所以每台机器都要单独指定管理网卡，数据网卡和外网网卡

- name: remove the base yum repository
  hosts: openstack[1:]
  remote_user: feiyu.liu
  sudo: yes
  tasks:
    - name: remove the base yum repository
      shell: rm -f /etc/yum.repos.d/CentOS-*

- name: install openstack common
  hosts: 10.100.23.15
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network, run_type: "once" ,manager_interface: enp3s0f0, data_interface: enp4s0f0, wan_interface: enp3s0f1,  manager_gateway: 10.100.23.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.115 }

- name: install openstack common
  hosts: 10.200.21.103
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network, run_type: "once", manager_interface: enp3s0f0, data_interface: enp4s0f0, wan_interface: enp3s0f1,  manager_gateway: 10.200.21.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.116  }

- name: install openstack common
  hosts: 10.200.21.111
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: enp3s0f0, data_interface: enp4s0f0, wan_interface: enp3s0f1,  manager_gateway: 10.200.21.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.117  }

- name: install openstack common
  hosts: 10.100.23.17
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: em1, data_interface: em3, wan_interface: em2,  manager_gateway: 10.100.23.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.118  }

- name: install openstack common
  hosts: 10.100.23.19
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: em1, data_interface: em3, wan_interface: em2,  manager_gateway: 10.100.23.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.119  }

- name: install openstack common
  hosts: 10.200.21.101
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: em1, data_interface: em3, wan_interface: em2,  manager_gateway: 10.200.21.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.120  }

- name: install openstack common
  hosts: 10.200.21.105
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: em1, data_interface: em3, wan_interface: em2,  manager_gateway: 10.200.21.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.121  }

- name: install openstack common
  hosts: 10.200.21.107
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: em1, data_interface: em3, wan_interface: em2,  manager_gateway: 10.200.21.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.122  }

- name: install openstack common
  hosts: 10.200.21.109
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: em1, data_interface: em3, wan_interface: em2,  manager_gateway: 10.200.21.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.123 }

- name: install openstack common
  hosts: 10.200.21.113
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: em1, data_interface: em3, wan_interface: em2,  manager_gateway: 10.200.21.254, wan_gateway: 10.200.21.254, wan_ip: 10.200.21.124  }
