---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#

# 1.系统初始化
- name: install openstack common
  hosts: 10.100.24.40
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - role: openstack-os-commom
# 2. 网络初始化
- name: remove the base yum repository
  hosts: 10.100.24.40
  remote_user: feiyu.liu
  sudo: yes
  tasks:
    - name: remove the base yum repository
      shell: rm -f /etc/yum.repos.d/CentOS-*

- name: install openstack common
  hosts: 10.100.24.40
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: enp3s0, data_interface: enp4s0, wan_interface: enp2s0,  manager_gateway: 10.100.24.254, wan_gateway: 10.200.24.254, wan_ip: 10.200.24.40  }

# 3. 安装配置 nova compute
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com
- name: install and config nova compute
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-nova-compute
  roles:
    - { role: openstack-nova-compute, openstack_ha_domain: 10.100.24.187 }

# 4. 安装配置 neutron compute
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com
- name: install and config neutron compute
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-neutron-compute
  roles:
    - { role: openstack-neutron-compute, openstack_ha_domain: 10.100.24.187 }
