---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# 步骤1：修改hosts文件，在openstack组加上新的compute，在openstack-nova-compute openstack-neutron-compute 添加新的compute并注释掉之前的compute。
# 步骤2：修改openstack-compute-recover.yml 文件，修改对应的hosts和一些参数。
# 步骤3：系统初始化完成后注释掉在执行；网络初始化后注释掉再执行，最后安装nova-compute和Neutron服务。

# 1.系统初始化
- name: install openstack common
  hosts: 10.100.24.36
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - role: openstack-os-common

# 2. 网络初始化
- name: remove the base yum repository
  hosts: 10.100.24.36
  remote_user: feiyu.liu
  sudo: yes
  tasks:
    - name: remove the base yum repository
      shell: rm -f /etc/yum.repos.d/CentOS-*

- name: install openstack common
  hosts: 10.100.24.36
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - { role: openstack-os-network,  run_type: "once", manager_interface: enp2s0, data_interface: enp3s0, wan_interface: enp3s1,  manager_gateway: 10.100.24.254, wan_gateway: 10.200.24.254, wan_ip: 10.200.24.36  }

# 3.安装mariadb数据库
- name: install mariadb cluster
  remote_user: feiyu.liu
  sudo: yes
  hosts: 10.100.24.36
  roles:
    - { role: openstack-galera-mariadb, galera_master: slave, bind_address: "{{ inventory_hostname }}" }

# 4.安装RabbitMQ
- name: install rabbitmq slave
  remote_user: feiyu.liu
  sudo: yes
  hosts: 10.100.24.36
  roles:
     - { role: openstack-rabbitmq, rabbitmq_master: slave, openstack_ha_domain: 10.100.24.187 }

# 4. 安装配置haproxy
- name: install and config haproxy
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-ha-haproxy
  roles:
    - { role: openstack-ha-haproxy, openstack_ha_vip: "10.100.24.187" }

# 根据需求是否要安装keepalived（要注意keepalived的角色master或者slave）
# - name: install and config keepalived
#   remote_user: feiyu.liu
#   sudo: yes
#   hosts: 10.100.24.36
#   roles:
#     - { role: openstack-ha-keepalived, keepalived_vip_ip: "10.100.24.187", keepalived_role: "BACKUP" , keepalived_vip_iface: "eth0" }

# 5. 安装keystone
- name: install and config keystone
  remote_user: feiyu.liu
  sudo: yes
  hosts: 10.100.24.36
  roles:
    - { role: openstack-keystone, service_create: not_create, openstack_ha_domain: 10.100.24.187 }

# 6.安装glance
- name: install and config the last glance hosts
  remote_user: feiyu.liu
  sudo: yes
  hosts: 10.100.24.36
  roles:
    - { role: openstack-glance, service_create: not_create, openstack_ha_domain: 10.100.24.187 }

# 7.安装nova-controller
- name: install and config nova controller the last hosts
  remote_user: feiyu.liu
  sudo: yes
  hosts: 10.100.24.36
  roles:
    - { role: openstack-nova-controller, service_create: not_create, openstack_ha_domain: 10.100.24.187 }

# 9. 安装neutron-controller
- name: install and config neutron controller the last hosts
  remote_user: feiyu.liu
  sudo: yes
  hosts: 10.100.24.36
  roles:
    - { role: openstack-neutron-controller, service_create: not_create, openstack_ha_domain: 10.100.24.187 }

# 10. 安装配置dashboard
- name: install and config openstack dashboard
  remote_user: feiyu.liu
  sudo: yes
  hosts: 10.100.24.36
  roles:
    - { role: openstack-dashboard }
