---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# 安装配置haproxy
# 配置变量 openstack_ha_vip: 10.100.24.187

- name: install and config haproxy
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-ha-keepalived 
  roles:
    - { role: openstack-ha-haproxy, openstack_ha_vip: "10.100.24.187" }
