---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# 这个主要是配置系统,安装基本操作系统软件,升级Centos系统等。
# 这一步升级完系统后会重启系统

- name: install openstack common
  hosts: openstack[1:]
  remote_user: feiyu.liu
  sudo: yes
  roles:
    - role: openstack-os-common
