---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# 安装配置 neutron compute
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com
- name: install and config neutron compute
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-compute 
  roles:
    - { role: openstack-neutron-compute, openstack_ha_domain: 10.100.24.187 }
