---
#
# Copyright (c) 2016 Feythin Lau <feythin.lau@gmail.com>
#
# 安装配置openstack集群
# 1. 安装配置数据库集群，默认配置主机组的第一台机器为master
# 配置变量： mysql_root_password: yunzongnet
- name: install mariadb cluster
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-galera-mariadb[0]
  roles:
    - { role: openstack-galera-mariadb, galera_master: master, bind_address: "{{ inventory_hostname }}" }

- name: install mariadb cluster
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-galera-mariadb:!openstack-galera-mariadb[0]
  roles:
    - { role: openstack-galera-mariadb, galera_master: slave, bind_address: "{{ inventory_hostname }}" }

- name: reconfigure mariadb master
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-galera-mariadb[0]
  roles:
    - { role: openstack-galera-mariadb-reconfigure, galera_master: master, bind_address: "{{ inventory_hostname }}" }

# 2. 安装配置RabbitMQ集群，默认配置主机组的第一台机器为master
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com

- name: install rabbitmq master
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq[0]
  roles:
     - { role: openstack-rabbitmq, rabbitmq_master: master, openstack_ha_domain: 10.100.23.28 }

- name: install rabbitmq slave
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq:!openstack-rabbitmq[0]
  roles:
     - { role: openstack-rabbitmq, rabbitmq_master: slave, openstack_ha_domain: 10.100.23.28 }

- name: set quene mirroring
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq[0]
  tasks:
    - name : enable queue mirroring
      shell: rabbitmqctl set_policy ha-all "\.*" '{"ha-mode":"all"}'

- name: add openstack user and add read write permissions
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-rabbitmq[0]
  tasks:
    - name: add openstack user
      shell: rabbitmqctl add_user openstack RABBIT_PASS
    - name: add read write permissions for openstack user
      shell: rabbitmqctl set_permissions openstack ".*" ".*" ".*"

# 3. 安装配置haproxy
# 配置变量 openstack_ha_vip: 10.100.24.180

- name: install and config haproxy
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-ha-haproxy
  roles:
    - { role: openstack-ha-haproxy, openstack_ha_vip: "10.100.23.28" }

# 4. 安装配置keepalived
# 配置变量 keepalived_vip_iface: "eth0"  keepalived_vip_ip: "192.168.1.1"

- name: install and config keepalived
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-ha-keepalived[0]
  roles:
    - { role: openstack-ha-keepalived, keepalived_vip_ip: "10.100.23.28", keepalived_role: "MASTER", keepalived_vip_iface: "enp3s0f0"  }

- name: install and config keepalived
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-ha-keepalived:!openstack-ha-keepalived[0]
  roles:
    - { role: openstack-ha-keepalived, keepalived_vip_ip: "10.100.23.28", keepalived_role: "BACKUP" , keepalived_vip_iface: "enp3s0f0" }

# 5. 安装配置keystone
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com

- name: install and config keystone
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-keystone[0]
  roles:
    - { role: openstack-keystone, service_create: once, openstack_ha_domain: 10.100.23.28 }

- name: install and config keystone
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-keystone:!openstack-keystone[0]
  roles:
    - { role: openstack-keystone, service_create: not_create, openstack_ha_domain: 10.100.23.28 }

# 6. 安装配置glance
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com

- name: install and config the frist glance host
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-glance[0]
  roles:
    - { role: openstack-glance, service_create: once, openstack_ha_domain: 10.100.23.28 }

- name: install and config the last glance hosts
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-glance:!openstack-glance[0]
  roles:
    - { role: openstack-glance, service_create: not_create, openstack_ha_domain: 10.100.23.28 }

# 7. 安装配置 nova controller
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com

- name: install and config nova controller the first host
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-nova-controller[0]
  roles:
    - { role: openstack-nova-controller, service_create: once, openstack_ha_domain: 10.100.23.28 }

- name: install and config nova controller the last hosts
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-nova-controller:!openstack-nova-controller[0]
  roles:
    - { role: openstack-nova-controller, service_create: not_create, openstack_ha_domain: 10.100.23.28 }

# 8. 安装配置 Neutron controller
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com

- name: install and config neutron controller the first host
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-neutron-controller[0]
  roles:
    - { role: openstack-neutron-controller, service_create: once, openstack_ha_domain: 10.100.23.28 }

- name: install and config neutron controller the last hosts
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-neutron-controller:!openstack-neutron-controller[0]
  roles:
    - { role: openstack-neutron-controller, service_create: not_create, openstack_ha_domain: 10.100.23.28 }

# 9. 安装配置dashboard

- name: install and config openstack dashboard
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-dashboard
  roles:
    - { role: openstack-dashboard }

# 10. 安装配置 nova compute
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com
- name: install and config nova compute
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-nova-compute
  roles:
    - { role: openstack-nova-compute, openstack_ha_domain: 10.100.23.28 }

# 11. 安装配置 neutron compute
# 配置变量 openstack_ha_domain: controllervip1.test.yunzongnet.com
- name: install and config neutron compute
  remote_user: feiyu.liu
  sudo: yes
  hosts: openstack-neutron-compute
  roles:
    - { role: openstack-neutron-compute, openstack_ha_domain: 10.100.23.28 }
